version: "3"
services:
  app:
    restart: always
    build: .
    ports:
      - "2000:3000"
    links:
      - mongo
    networks:
      - my-network
    volumes:
      - ./src:/usr/src/app
  mongo:
    container_name: mongo_santa
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
